# Generated by Django 4.0.4 on 2022-07-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_project_owner_alter_organization_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
