# Generated by Django 4.0.4 on 2022-07-12 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0007_remove_project_owner_delete_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='access_policies',
            field=models.CharField(choices=[('r', 'read'), ('w', 'write'), ('a', 'admin')], default='r', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(help_text='User Ctrl to select more than one member', related_name='project_members', through='organization.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Project name', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='public',
            field=models.BooleanField(help_text='Is it publicly viewable?'),
        ),
    ]
