# Generated by Django 4.0.4 on 2022-07-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_membership_access_policies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=False, help_text='Current active project'),
        ),
    ]
