# Generated by Django 4.0.4 on 2022-07-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_project_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='active',
        ),
        migrations.AddField(
            model_name='membership',
            name='active',
            field=models.BooleanField(default=False, help_text='Current active project'),
        ),
    ]
