# Generated by Django 4.0.4 on 2022-07-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_remove_project_active_membership_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='active',
        ),
    ]
