# Generated by Django 4.0.4 on 2022-07-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_remove_membership_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, help_text='Project description', max_length=500, null=True),
        ),
    ]
