# Generated by Django 4.0.4 on 2022-07-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_tablefilter_remove_recipe_category_recipe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablefilter',
            name='options',
        ),
    ]
