# Generated by Django 5.0.7 on 2024-07-10 16:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('info', 'Cyan'), ('warning', 'Yellow'), ('danger', 'Red'), ('light', 'White'), ('dark', 'Black')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reactive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('state', models.IntegerField(choices=[(0, 'Solid'), (1, 'Liquid')])),
                ('mm', models.FloatField(blank=True, help_text='g/mol', null=True)),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('concentration_unit', models.CharField(blank=True, choices=[('mol', 'M'), ('mmol', 'mM'), ('grlt', 'mg / ml'), ('vvp', 'Volume / Volume %'), ('wvp', 'Weight / Volume %')], max_length=4, null=True)),
                ('is_autoclavable', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concentration', models.FloatField()),
                ('concentration_unit', models.CharField(choices=[('mol', 'M'), ('mmol', 'mM'), ('grlt', 'mg / ml'), ('vvp', 'Volume / Volume %'), ('wvp', 'Weight / Volume %')], max_length=4)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reactive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocols.reactive')),
            ],
            options={
                'ordering': ['reactive'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=4, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('ph', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('components', models.ManyToManyField(blank=True, to='protocols.component')),
                ('optional_components', models.ManyToManyField(blank=True, related_name='optional_components', to='protocols.component')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shared_to_project', models.ManyToManyField(blank=True, help_text='Use CTRL for multiple select', to='organization.project')),
                ('category', models.ManyToManyField(blank=True, help_text='Use CTRL for multiple select', to='protocols.tablefilter')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=4, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('ph', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('optional_components', models.ManyToManyField(blank=True, to='protocols.component')),
                ('recipe', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='protocols.recipe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
