# Generated by Django 4.0.4 on 2022-07-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('info', 'Cyan'), ('warning', 'Yellow'), ('danger', 'Red'), ('light', 'White'), ('dark', 'Black')], max_length=10, null=True)),
                ('options', models.CharField(blank=True, help_text="Format: 'x|X,y|Y'. Left side is the name of the filter and right side is the start-with text", max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(blank=True, to='protocols.tablefilter'),
        ),
    ]
