# Generated by Django 5.0.7 on 2024-07-10 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_policies', models.CharField(choices=[('r', 'read'), ('w', 'write'), ('a', 'admin')], default='r', max_length=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Project name', max_length=128)),
                ('description', models.CharField(blank=True, help_text='Project description', max_length=500, null=True)),
                ('public', models.BooleanField(help_text='Is it publicly viewable?')),
                ('members', models.ManyToManyField(help_text='User Ctrl to select more than one member', related_name='project_members', through='organization.Membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.project'),
        ),
    ]
