# Generated by Django 5.0.7 on 2025-04-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assembly_standard',
            field=models.CharField(blank=True, choices=[('ytk', 'Yeast Toolkit'), ('loop', 'Loop'), ('gb', 'Golden Braid 2.0')], help_text='Project assembly standard', max_length=10, null=True),
        ),
    ]
