# Generated by Django 4.0.4 on 2022-07-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_rename_person_membership_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
