# Generated by Django 4.0.4 on 2022-05-24 18:39

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlasmidTypes',
            new_name='PlasmidType',
        ),
        migrations.AlterField(
            model_name='glicerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='UptnK3YvDcQ6uDKypexN6i', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='5aoECRPXkFwyJmDBgBfU4h', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='2bw9qjEiWPUtq2rXmi3qH3', editable=False, max_length=22),
        ),
    ]
