# Generated by Django 4.0.4 on 2022-07-11 14:51

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='ctoqkfaFCR2MyS8VJ67QED', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='9bv4n56oQEChXWBMUuQYoi', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='VfdkfuQrpfuFqsfxMKXu5F', editable=False, max_length=22),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
