# Generated by Django 4.0.4 on 2022-05-24 18:45

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_plasmidtypes_plasmidtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glicerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='S942jmK8wZAoCrPsRjact9', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='oXFeHA4tcE9EdZeJwTMXmL', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmidtype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='AN3N8fTqbhUwf8PfDY3YF2', editable=False, max_length=22),
        ),
    ]
