# Generated by Django 4.0.4 on 2022-05-24 19:52

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_glicerolstock_qr_id_alter_plasmid_qr_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasmidAuthor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='plasmid',
            name='cloning_method',
        ),
        migrations.RemoveField(
            model_name='plasmid',
            name='expression_or_cloning',
        ),
        migrations.AlterField(
            model_name='glicerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='MkqNZZ3HedueDJQ3mDAKFN', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='NBCv5U4qLqdC6uVLEb4n6i', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmidtype',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='BXqyEWvuzshM28pQmy4wBj', editable=False, max_length=22),
        ),
    ]
