# Generated by Django 4.0.4 on 2022-05-27 18:20

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_plasmidauthor_remove_plasmid_cloning_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resistance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('three_letter_code', models.CharField(blank=True, max_length=3)),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='plasmid',
            name='resistances_plant',
        ),
        migrations.AlterField(
            model_name='glicerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='ncKYCCSUWsDvLwxndAMK4A', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.plasmidauthor'),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='jMGfRmdLriZbNNw7KpMjA8', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='bGk8sxH9PEtFjWbbTNbXd8', editable=False, max_length=22),
        ),
        migrations.AddField(
            model_name='plasmid',
            name='resistances2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.resistance'),
        ),
    ]
