# Generated by Django 4.0.4 on 2022-05-31 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_resistance_remove_plasmid_resistances_plant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlycerolStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('box_row', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], max_length=1, null=True)),
                ('box_column', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], null=True)),
                ('qr_id', shortuuidfield.fields.ShortUUIDField(blank=True, default='cD8McNEMdV33nYeEynTZ3y', editable=False, max_length=22)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('box', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.box')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.glycerolstock')),
            ],
            options={
                'ordering': ['strain', 'plasmid'],
            },
        ),
        migrations.CreateModel(
            name='TableFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('info', 'Cyan'), ('warning', 'Yellow'), ('danger', 'Red'), ('light', 'White'), ('dark', 'Black')], max_length=10, null=True)),
                ('options', models.CharField(blank=True, help_text="Format: 'x|X,y|Y'. Left side is the name of the filter and right side is the start-with text", max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='plasmid',
            name='resistances2',
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='hejA5e6dCvpUqx7r7bsnFi', editable=False, max_length=22),
        ),
        migrations.RemoveField(
            model_name='plasmid',
            name='resistances',
        ),
        migrations.AddField(
            model_name='plasmid',
            name='resistances',
            field=models.ManyToManyField(blank=True, help_text='Use CTRL for multiple select', related_name='+', to='inventory.resistance'),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='eXEuTy9LzkxR92fsFhYRE8', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='restrictionenzyme',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='strain',
            name='resistances',
        ),
        migrations.AddField(
            model_name='strain',
            name='resistances',
            field=models.ManyToManyField(blank=True, help_text='Use CTRL for multiple select', related_name='+', to='inventory.resistance'),
        ),
        migrations.DeleteModel(
            name='GlicerolStock',
        ),
        migrations.AddField(
            model_name='glycerolstock',
            name='plasmid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.plasmid'),
        ),
        migrations.AddField(
            model_name='glycerolstock',
            name='strain',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.strain'),
        ),
    ]
