# Generated by Django 4.0.4 on 2022-05-31 12:53

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_restrictionenzyme_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='TPZTZ97ZaStqe9N3eZovTN', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='bNXEbxkmWREHovTJ5j3qnf', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='dzhcHmcwKFTYJFCeiPQf9q', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='restrictionenzyme',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
