# Generated by Django 4.0.4 on 2022-06-02 15:05

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_glycerolstock_qr_id_alter_plasmid_qr_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='plasmids_by_l0_part_type',
        ),
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='k8bxNFGGGBNfrYCFpWPRWw', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='7KMNab5EdLc242hAWoxeEE', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='NnQV4whfxCs3wJ9zuEgnkv', editable=False, max_length=22),
        ),
    ]
