# Generated by Django 4.0.4 on 2022-07-12 16:01

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_glycerolstock_qr_id_alter_plasmid_qr_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plasmid',
            name='sequencing_ab1_file_1',
        ),
        migrations.RemoveField(
            model_name='plasmid',
            name='sequencing_ab1_file_2',
        ),
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='ZUKv6m2H7RTzMKGVQYouw2', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='ST5q8UKhUs3je2gFMpFmhX', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='J6GCiNLWULNYcxVW2jduBD', editable=False, max_length=22),
        ),
    ]
