# Generated by Django 4.0.4 on 2022-07-14 12:37

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_plasmid_author_alter_glycerolstock_qr_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plasmid',
            old_name='resistances',
            new_name='selectable_markers',
        ),
        migrations.RenameField(
            model_name='strain',
            old_name='resistances',
            new_name='selectable_markers',
        ),
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='KupgY9MLRTFd4JFpgattYg', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='LmgLWZTUYw8KWYmkVGer69', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='43oEFfuNvbNawPt3cAvz7f', editable=False, max_length=22),
        ),
    ]
