# Generated by Django 4.0.4 on 2022-07-14 15:07

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_membership_access_policies_and_more'),
        ('inventory', '0014_rename_resistances_plasmid_selectable_markers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasmid',
            name='project',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='organization.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='7tqyBYy4vXVEHutJjDqNYD', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='ejuXmaApec4HSHY83EHPm8', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='4yTHX45rapSNAv6UDFwQ6c', editable=False, max_length=22),
        ),
    ]
