# Generated by Django 4.0.4 on 2022-07-25 11:49

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_glycerolstock_project_alter_glycerolstock_qr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glycerolstock',
            name='box',
            field=models.ForeignKey(help_text='Click box position (below) to autocomplete', on_delete=django.db.models.deletion.CASCADE, to='inventory.box'),
        ),
        migrations.AlterField(
            model_name='glycerolstock',
            name='box_column',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1, help_text='Click box position (below) to autocomplete'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glycerolstock',
            name='box_row',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], default=1, help_text='Click box position (below) to autocomplete', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='VqoSaUaA5u7o6TDjMyHnVH', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='oLPFha5Fpd8iZ6jCY2xbB7', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='FEgJVMtRwoZECUL2duLLfa', editable=False, max_length=22),
        ),
    ]
