# Generated by Django 4.0.4 on 2022-11-29 15:44

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_plasmid_idx_alter_glycerolstock_qr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='2otJdrBU8CfuHPisQq6YWP', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='fw4VzW7ZoLJven3veMgMox', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='23ddVkco5NUcjVQRwBNZQx', editable=False, max_length=22),
        ),
    ]
