# Generated by Django 4.2 on 2023-07-25 15:24

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_strain_for_primary_gs_alter_glycerolstock_qr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasmid',
            name='public_visibility',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='YAjtws6Rdy5ZTwNGYSS44M', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='N6rCRoBDVY9PUhRHotmQZA', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='Vu9NT6M9vMYAK9WkybwRZz', editable=False, max_length=22),
        ),
    ]
