# Generated by Django 5.0.7 on 2025-04-24 12:52

import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='V7Vj24LQN9xCR4WVHWtyKF', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='description',
            field=models.CharField(blank=True, help_text='Allows markdown', max_length=1000),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='level',
            field=models.IntegerField(blank=True, choices=[(None, 'Not defined'), (0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], null=True),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='DWo2p8jPAWtA89mBfVraXz', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='fdZEfJSApBZ3QwpLgCLiJ7', editable=False, max_length=22),
        ),
    ]
