# Generated by Django 5.0.7 on 2025-04-24 12:55

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_glycerolstock_qr_id_alter_plasmid_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='4x53x8NU3UfG8ZrButBGvM', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='nhGbLbxvsaQApuNM5Vv9YL', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='mARFRjNZXH2YEgs4iGQCy3', editable=False, max_length=22),
        ),
    ]
