# Generated by Django 5.0.7 on 2026-01-21 13:44

import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_glycerolstock_qr_id_alter_plasmid_qr_id_and_more'),
        ('organization', '0002_project_assembly_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='7syBJCi5LMu3QN9JHTFjy6', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='bjeChrKPoPFADYs84ay2fH', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='Qg5Exd2AG2ZGWgAuhSzncF', editable=False, max_length=22),
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Experiment name', max_length=128)),
                ('description', models.CharField(blank=True, help_text='Experiment description', max_length=500, null=True)),
                ('plasmids', models.ManyToManyField(blank=True, related_name='+', to='inventory.plasmid')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.project')),
            ],
        ),
    ]
