# Generated by Django 6.0.7 on 2026-07-31 19:05

import django.db.models.deletion
import inventory.models
import inventory.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_glycerolstock_qr_id_alter_plasmid_qr_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SangerRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('detected_orientation', models.CharField(choices=[('forward', 'Forward'), ('reverse', 'Reverse complement'), ('ambiguous', 'Ambiguous'), ('unmapped', 'Unmapped')], default='unmapped', max_length=20)),
                ('forced_orientation', models.CharField(blank=True, choices=[('forward', 'Forward'), ('reverse', 'Reverse complement'), ('ambiguous', 'Ambiguous'), ('unmapped', 'Unmapped')], default='', max_length=20)),
                ('raw_sequence', models.TextField(blank=True)),
                ('trimmed_sequence', models.TextField(blank=True)),
                ('selected_source', models.CharField(blank=True, max_length=20)),
                ('parsing_result', models.JSONField(blank=True, default=dict)),
                ('quality_metrics', models.JSONField(blank=True, default=dict)),
                ('alignment_metrics', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('is_usable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SangerReadFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('ab1', 'AB1'), ('phd1', 'PHD.1'), ('seq', 'SEQ')], max_length=10)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to=inventory.models.sanger_read_file_upload_to)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inventory.sangerread')),
            ],
            options={
                'ordering': ['format', 'original_name'],
            },
        ),
        migrations.CreateModel(
            name='SangerVerificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('colony', models.CharField(blank=True, max_length=100)),
                ('sample', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('automated_state', models.CharField(choices=[('PASS', 'Verifica'), ('REVIEW', 'Requiere revisión'), ('FAIL', 'No verifica'), ('NO_DATA', 'Sin datos utilizables')], default='NO_DATA', max_length=20)),
                ('automated_reasons', models.JSONField(blank=True, default=list)),
                ('combined_metrics', models.JSONField(blank=True, default=dict)),
                ('manual_decision', models.CharField(blank=True, choices=[('', 'Pendiente/requiere revisión'), ('VERIFIED', 'Verificada'), ('REJECTED', 'No verificada'), ('PENDING', 'Pendiente/requiere revisión')], default='', max_length=20)),
                ('manual_decision_at', models.DateTimeField(blank=True, null=True)),
                ('clustal_file', models.FileField(blank=True, null=True, upload_to='uploads/sequencing_clustal', validators=[inventory.validators.clustal_validate])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanger_verification_runs', to=settings.AUTH_USER_MODEL)),
                ('manual_decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanger_manual_decisions', to=settings.AUTH_USER_MODEL)),
                ('plasmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanger_verification_runs', to='inventory.plasmid')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SangerVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordinate', models.PositiveIntegerField(help_text='0-based plasmid coordinate')),
                ('variant_type', models.CharField(max_length=20)),
                ('expected_base', models.CharField(blank=True, max_length=20)),
                ('observed_base', models.CharField(blank=True, max_length=20)),
                ('quality', models.IntegerField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('read', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.sangerread')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.sangerverificationrun')),
            ],
            options={
                'ordering': ['coordinate', 'variant_type'],
            },
        ),
        migrations.AddField(
            model_name='sangerread',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='inventory.sangerverificationrun'),
        ),
    ]
