# Generated by Django 6.0.7 on 2026-07-31 19:06

import inventory.models
import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_sangerread_alter_glycerolstock_qr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=inventory.models.generate_shortuuid, editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=inventory.models.generate_shortuuid, editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=inventory.models.generate_shortuuid, editable=False, max_length=22),
        ),
    ]
