# Generated by Django 6.0.7 on 2026-07-31 19:15

import inventory.models
import inventory.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_glycerolstock_qr_id_alter_plasmid_qr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sangerreadfile',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to=inventory.models.sanger_read_file_upload_to),
        ),
        migrations.AlterField(
            model_name='sangerverificationrun',
            name='clustal_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/sequencing_clustal', validators=[inventory.validators.clustal_validate]),
        ),
    ]
