# Generated by Django 6.0.7 on 2026-07-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_sangerreadfile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sangerverificationrun',
            name='manual_decision',
            field=models.CharField(blank=True, choices=[('', 'Pendiente'), ('VERIFIED', 'Verificada'), ('REJECTED', 'No verificada'), ('PENDING', 'Pendiente')], default='', max_length=20),
        ),
    ]
