# Generated by Django 6.0.7 on 2026-07-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_sangerverificationrun_manual_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sangerverificationrun',
            name='manual_decision',
            field=models.CharField(blank=True, choices=[('', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Not verified'), ('PENDING', 'Pending')], default='', max_length=20),
        ),
    ]
