# Generated by Codex on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_sangerverificationrun_manual_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sangerverificationrun',
            name='manual_decision',
            field=models.CharField(blank=True, choices=[('', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Not verified'), ('INCONCLUSIVE', 'Inconclusive'), ('PENDING', 'Pending')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sangerverificationrun',
            name='manual_decision_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sangerverificationrun',
            name='manual_decision_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
