# Generated by Codex on 2026-08-12

from django.db import migrations


def seed_default_ytk_enzymes(apps, schema_editor):
    RestrictionEnzyme = apps.get_model("inventory", "RestrictionEnzyme")
    for enzyme_name in ("BsaI", "BsmBI"):
        RestrictionEnzyme.objects.get_or_create(
            name=enzyme_name,
            hf_version=False,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_sanger_decision_evidence"),
    ]

    operations = [
        migrations.RunPython(seed_default_ytk_enzymes, migrations.RunPython.noop),
    ]
