# Generated by Django 6.0.7 on 2026-08-12 17:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


LEGACY_RESTRICTION_BUFFERS = (
    ('activity_buffer_1_1', 'NEB 1.1'),
    ('activity_buffer_2_1', 'NEB 2.1'),
    ('activity_buffer_3_1', 'NEB 3.1'),
    ('activity_buffer_CS', 'NEB CutSmart'),
    ('activity_buffer_aari', 'Thermo AarI'),
)


def migrate_legacy_restriction_buffers(apps, schema_editor):
    RestrictionBuffer = apps.get_model('inventory', 'RestrictionBuffer')
    RestrictionEnzyme = apps.get_model('inventory', 'RestrictionEnzyme')
    RestrictionEnzymeBuffer = apps.get_model('inventory', 'RestrictionEnzymeBuffer')

    for restriction_enzyme in RestrictionEnzyme.objects.all():
        for field_name, buffer_name in LEGACY_RESTRICTION_BUFFERS:
            activity_percent = getattr(restriction_enzyme, field_name, None)
            if activity_percent is None:
                continue
            buffer, _created = RestrictionBuffer.objects.get_or_create(name=buffer_name)
            RestrictionEnzymeBuffer.objects.get_or_create(
                restriction_enzyme=restriction_enzyme,
                buffer=buffer,
                defaults={'activity_percent': activity_percent},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_seed_default_ytk_enzymes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictionBuffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestrictionEnzymeBuffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('buffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enzyme_links', to='inventory.restrictionbuffer')),
                ('restriction_enzyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffer_links', to='inventory.restrictionenzyme')),
            ],
            options={
                'ordering': ['buffer__name'],
            },
        ),
        migrations.AddField(
            model_name='restrictionenzyme',
            name='buffers',
            field=models.ManyToManyField(blank=True, related_name='restriction_enzymes', through='inventory.RestrictionEnzymeBuffer', to='inventory.restrictionbuffer'),
        ),
        migrations.AddConstraint(
            model_name='restrictionenzymebuffer',
            constraint=models.UniqueConstraint(fields=('restriction_enzyme', 'buffer'), name='unique_restriction_enzyme_buffer'),
        ),
        migrations.RunPython(migrate_legacy_restriction_buffers, migrations.RunPython.noop),
    ]
