# Generated by Codex on 2026-08-12

from django.db import migrations


DEFAULT_RESTRICTION_ENZYMES = (
    {
        "name": "BsaI",
        "hf_version": False,
    },
    {
        "name": "BsaI",
        "hf_version": True,
        "link_datasheet": "https://www.neb.com/en/products/r3733-bsai-hf-v2",
        "description": "Default YTK enzyme seeded from the NEB BsaI-HF v2 datasheet.",
        "buffer_activities": {
            "NEB 1.1": 100,
            "NEB 2.1": 100,
            "NEB 3.1": 100,
            "NEB CutSmart": 100,
        },
    },
    {
        "name": "BsmBI",
        "hf_version": False,
        "link_datasheet": "https://www.neb.com/en/products/r0739-bsmbi-v2",
        "description": "Default YTK enzyme seeded from the NEB BsmBI v2 datasheet. NEBuffer r1.1 activity is reported by NEB as <10%.",
        "buffer_activities": {
            "NEB 1.1": 10,
            "NEB 2.1": 50,
            "NEB 3.1": 100,
            "NEB CutSmart": 25,
        },
    },
)


def seed_ytk_enzyme_metadata(apps, schema_editor):
    RestrictionBuffer = apps.get_model("inventory", "RestrictionBuffer")
    RestrictionEnzyme = apps.get_model("inventory", "RestrictionEnzyme")
    RestrictionEnzymeBuffer = apps.get_model("inventory", "RestrictionEnzymeBuffer")

    for definition in DEFAULT_RESTRICTION_ENZYMES:
        restriction_enzyme, _created = RestrictionEnzyme.objects.get_or_create(
            name=definition["name"],
            hf_version=definition["hf_version"],
        )

        update_fields = []
        for field_name in ("link_datasheet", "description"):
            value = definition.get(field_name)
            if value and getattr(restriction_enzyme, field_name) != value:
                setattr(restriction_enzyme, field_name, value)
                update_fields.append(field_name)
        if update_fields:
            restriction_enzyme.save(update_fields=update_fields)

        for buffer_name, activity_percent in definition.get("buffer_activities", {}).items():
            restriction_buffer, _created = RestrictionBuffer.objects.get_or_create(name=buffer_name)
            enzyme_buffer, created = RestrictionEnzymeBuffer.objects.get_or_create(
                restriction_enzyme=restriction_enzyme,
                buffer=restriction_buffer,
                defaults={"activity_percent": activity_percent},
            )
            if not created and enzyme_buffer.activity_percent != activity_percent:
                enzyme_buffer.activity_percent = activity_percent
                enzyme_buffer.save(update_fields=["activity_percent"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_restrictionbuffer_restrictionenzymebuffer_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_ytk_enzyme_metadata, migrations.RunPython.noop),
    ]
