# Generated by Django 4.0.4 on 2022-07-14 12:30

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_plasmid_sequencing_ab1_file_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plasmid',
            name='author',
        ),
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='D6eUFgMvhuBmvoDpTbnqqr', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='backbone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.plasmid'),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='CFaP7z9skq5EQTkFCveAkk', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.plasmidtype'),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='2TmGhUzYL873cXGvWEyEnr', editable=False, max_length=22),
        ),
    ]
