# Generated by Django 6.0.7 on 2026-08-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_experiment_optional_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="sangerreadfile",
            name="primer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sanger_read_files",
                to="inventory.primer",
            ),
        ),
    ]
