# Generated by Django 6.0.7 on 2026-08-26

import datetime
import re

from django.db import migrations, models
from django.utils import timezone


def parse_file_datetime(source_file):
    match = re.search(
        r"(?<!\d)(20\d{2})-(\d{2})-(\d{2})-(\d{2})-(\d{2})-(\d{2})(?!\d)",
        source_file.original_name or "",
    )
    if match:
        try:
            return datetime.datetime.strptime("-".join(match.groups()), "%Y-%m-%d-%H-%M-%S")
        except ValueError:
            pass

    metadata = source_file.metadata or {}
    date_value = str(metadata.get("run_start_date") or "").strip()
    time_value = str(metadata.get("run_start_time") or "").strip()
    if date_value and time_value:
        try:
            return datetime.datetime.fromisoformat("{} {}".format(date_value, time_value))
        except ValueError:
            return None
    return None


def populate_sequencing_datetimes(apps, schema_editor):
    run_model = apps.get_model("inventory", "SangerVerificationRun")
    for run in run_model.objects.filter(sequencing_datetime__isnull=True).iterator():
        datetimes = [
            run_datetime
            for read in run.reads.all().prefetch_related("files")
            for source_file in read.files.all()
            for run_datetime in [parse_file_datetime(source_file)]
            if run_datetime
        ]
        if datetimes:
            run.sequencing_datetime = timezone.make_aware(max(datetimes))
            run.save(update_fields=["sequencing_datetime"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_remove_primer_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="sangerverificationrun",
            name="sequencing_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(populate_sequencing_datetimes, migrations.RunPython.noop),
    ]
