# Generated by Django 4.0.4 on 2022-07-27 12:26

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_project_description'),
        ('inventory', '0023_alter_glycerolstock_qr_id_alter_plasmid_qr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='project',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='organization.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='grA5X5tTpRhrSWEQT9zbGk', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='Usgtec8fBedpprxsQMwBbH', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='MqF8eH2BbQoKhkEVF7tv8Z', editable=False, max_length=22),
        ),
    ]
