# Generated by Django 4.2 on 2023-04-26 11:20

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_alter_glycerolstock_qr_id_alter_plasmid_qr_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plasmid',
            old_name='clustal',
            new_name='sequencing_clustal_file',
        ),
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='CcHwM2jtkqW7BbaGva5gXm', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='VktM4nwJE8L4kdJeqRKr5p', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='dYKP8e3JBKqe3YMs3QSrhk', editable=False, max_length=22),
        ),
    ]
