# Generated by Django 4.2 on 2023-04-27 15:28

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_rename_clustal_plasmid_sequencing_clustal_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='for_primary_gs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='glycerolstock',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='jhub5cVFJqQRbtBDcx37Xx', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='plasmid',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='cdiTRqVbQJfuYF5RavDLuL', editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='primer',
            name='qr_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='G2usv558ENbLUf6K5kFZUi', editable=False, max_length=22),
        ),
    ]
